# Generated by Django 5.1.5 on 2025-01-24 11:17

import shared.file_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelimage',
            name='image',
            field=models.ImageField(upload_to=shared.file_utils.file_upload_path, validators=[shared.file_utils.validate_five_mb_image_size]),
        ),
    ]
